/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  timmy
 * Created: 15/05/2021
 */

SELECT 
CUSTOMERTABLE.CUSTOMERID, CUSTOMERTABLE.CUSTOMERTYPE,
USERTABLE.FIRSTNAME, USERTABLE.LASTNAME, USERTABLE.DOB, USERTABLE.GENDER, USERTABLE.EMAILADDRESS, 
USERTABLE.PASSWORD, USERTABLE.PHONENUMBER, USERTABLE.STREETNUMBER, USERTABLE.STREETNAME, USERTABLE.POSTCODE,
CUSTOMERTABLE.ORDERID, CUSTOMERTABLE.REGISTERED
FROM USERTABLE
INNER JOIN CUSTOMERTABLE ON USERTABLE.USERID = CUSTOMERTABLE.USERID
WHERE USERTABLE.FIRSTNAME = 'Jim'
AND USERTABLE.LASTNAME = 'Neil' AND CUSTOMERTABLE.CUSTOMERTYPE = 'Individual';