INSERT INTO USERTABLE(FIRSTNAME, LASTNAME, PASSWORD, DOB,GENDER, PHONENUMBER, EMAILADDRESS, STREETNUMBER, STREETNAME, POSTCODE)
VALUES ('John', 'Seed', 'password', '02/02/2020','Male', '123123123', 'somethin@email.com', 23 , 'phlips street', 1233 );
